apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: venuego-public-ingress
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          # Auth endpoints should be public (register/login/logout)
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 6235
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: venuego-protected-ingress
  annotations:
    konghq.com/plugins: jwt-auth,inject-userid-post
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: my-user-app
                port:
                  number: 6238
          - path: /api/v1/venues
            pathType: Prefix
            backend:
              service:
                name: venue-service
                port:
                  number: 6236
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: venue-service
                port:
                  number: 6236
          - path: /api/v1/tickets
            pathType: Prefix
            backend:
              service:
                name: ticketing-service
                port:
                  number: 6240
          - path: /api/checkin
            pathType: Prefix
            backend:
              service:
                name: checkin-service
                port:
                  number: 6237
          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 6239
          - path: /echo
            pathType: Prefix
            backend:
              service:
                name: test-echo-service
                port:
                  number: 80