apiVersion: v1
kind: Secret
metadata:
  name: test-user-jwt-secret
  namespace: default
  labels:
    konghq.com/credential: jwt
  annotations:
    kubernetes.io/ingress.class: kong
type: Opaque
stringData:
  key: "venuego-auth-service"       # 必须匹配 JWT 载荷里的 iss
  algorithm: "RS256"
  rsa_public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4kBl9ylKXrWhlgXWoIav
    utQlhVIAkQ2N5THQh/3dBBUeCP5PxyDbNTxZVqNF2Q5ALW+vyVu4UKidO50T8Qfe
    I/gKshYt88iPHPDaLOKqENKWdCsgD6WLgg4QFx0MF9pfh3hERCcHQ6Ly6xVZYZgC
    xUSL3igLE3ML953Z4glXbAGczAgPckJ3+qCryAw30PmZ0B2nlvIiFUh5VSdqi9dS
    xIu/GHFSfafnjW9697doFUESmzoxB9NSK0/YzMYLhCRtzMin08isfBoAm2bIsuFQ
    Ugy+0aNULtjIIoUeuGWWnDwvQ/2OLlLFHFEUvgYDLRVcSF/BI5akeRzlF225l1eX
    ZwIDAQAB
    -----END PUBLIC KEY-----
