server:
  port: 6240

grpc:
  server:
    port: 9240

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2s

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER}
  producer:
    group: ticketing-producer-group

ticketing:
  mq:
    purchase-topic: ticketing-purchase-success
    inventory-consumer-group: ticketing-inventory-consumer
    order-consumer-group: ticketing-order-consumer
  redis:
    key:
      inventory-prefix: "ticket:ivtr:"
      info-prefix: "ticket:info:"
      ordered-prefix: "ticket:ordered:"

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    # com.happy.TicketingService.service.impl: DEBUG
    # com.happy.TicketingService.controller: DEBUG
